stages:
  prepare_data:
    cmd: python src/data_prep.py
    deps:
      - data/raw
      - src/data_prep.py
    params:
      - base.use_augmented
    outs:
      - data/processed

  train_lenet:
    cmd: python src/train.py --model lenet
    deps:
      - src/train.py
      - src/config.py
      - data/processed
      - src/registry.py
      - src/architectures/CNNs/LeNet_5.py
    params:
      - base
      - models.lenet
    outs:
      - experiments/lenet/model.pth
      - experiments/lenet/training_log.csv

  evaluate_lenet:
    cmd: python src/evaluate.py --model lenet
    deps:
      - data/processed
      - src/evaluate.py
      - src/config.py
      - src/registry.py
      - experiments/lenet/model.pth
      - src/architectures/CNNs/LeNet_5.py
    params:
      - models.lenet
    metrics:
      - experiments/lenet/metrics.json:
          cache: false

  train_pintee_cnn:
    cmd: python src/train.py --model pintee_cnn
    deps:
      - src/train.py
      - src/config.py
      - data/processed
      - src/registry.py
      - src/architectures/CNNs/VGG_ResNet_Hybrid.py
    params:
      - base
      - models.pintee_cnn
    outs:
      - experiments/pintee_cnn/model.pth
      - experiments/pintee_cnn/training_log.csv

  evaluate_pintee_cnn:
    cmd: python src/evaluate.py --model pintee_cnn
    deps:
      - data/processed
      - src/evaluate.py
      - src/config.py
      - src/registry.py
      - experiments/pintee_cnn/model.pth
      - src/architectures/CNNs/VGG_ResNet_Hybrid.py
    params:
      - models.pintee_cnn
    metrics:
      - experiments/pintee_cnn/metrics.json:
          cache: false

  train_convnext_v1:
    cmd: python src/train.py --model convnext_v1
    deps:
      - src/train.py
      - src/config.py
      - data/processed
      - src/registry.py
      - src/architectures/CNNs/ConvNeXt_v1_Adapted.py
    params:
      - base
      - models.convnext_v1
    outs:
      - experiments/convnext_v1/model.pth
      - experiments/convnext_v1/training_log.csv

  evaluate_convnext_v1:
    cmd: python src/evaluate.py --model convnext_v1
    deps:
      - data/processed
      - src/evaluate.py
      - src/config.py
      - src/registry.py
      - experiments/convnext_v1/model.pth
      - src/architectures/CNNs/ConvNeXt_v1_Adapted.py
    params:
      - models.convnext_v1
    metrics:
      - experiments/convnext_v1/metrics.json:
          cache: false